run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - unused
    - typecheck
    - gocyclo        # complexity
    - revive         # style/lint successor to golint
  disable:
    - depguard       # can enable later to restrict imports
    - dupl           # can be noisy for handlers

linters-settings:
  gocyclo:
    min-complexity: 12
  revive:
    rules:
      - name: blank-imports
      - name: var-naming
      - name: receiver-naming

issues:
  exclude-dirs:
    - vendor
    - tmp
    - .git
  # Examples of patterns you might ignore later:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
    - path: internal/repository/
      text: "G101"    # example if you add a security linter later and need to ignore false positives

# Optional: per-package settings later if needed

